format = """
[](yellow)\
$os\
$username\
[](bg:red fg:yellow)\
$directory\
[](fg:red bg:green)\
$git_branch\
$git_status\
[](fg:green bg:blue)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:blue bg:purple)\
$docker_context\
[](fg:purple bg:cyan)\
$time\
[ ](fg:cyan)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:yellow"
style_root = "bg:yellow"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:yellow"
disabled = true # Disabled by default

[directory]
style = "bg:red"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:purple"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:green"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:green"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:cyan"
format = '[ ♥ $time ]($style)'
